FROM python:3.11-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Use SQLite, so no Postgres, no netcat
# No entrypoint waiting for DB

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:create_app()"]
