"""Add is_admin field

Revision ID: 733fd72fcee0
Revises: 592e2210c415
Create Date: 2025-10-27 23:20:09.408574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733fd72fcee0'
down_revision = '592e2210c415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
